#115. Update certs for deploy

diff --git a/docker/Dockerfile.ui b/docker/Dockerfile.ui
--- a/docker/Dockerfile.ui
+++ b/docker/Dockerfile.ui
@@ -21,18 +21,19 @@ COPY ./fantasy_helper/ui/package.json /fantasy_helper
 
 RUN npm install
 COPY ./fantasy_helper/ui /fantasy_helper
-COPY ./certs /fantasy_helper/certs
+
+# COPY ./cert[s] /fantasy_helper/certs || true
+# Copy certificates only if they exist (for local development with HTTPS)
+# COPY ./cert[s] /fantasy_helper/certs/ || true
+
 RUN npm run build && \
     apk add --no-cache ca-certificates && \
     update-ca-certificates
 
-
-# EXPOSE 8501
 EXPOSE 4173
-# HEALTHCHECK CMD curl --fail http://localhost:4173/ --insecure
-HEALTHCHECK --interval=30s --timeout=3s \
-  CMD curl --fail https://localhost:4173/ --insecure || exit 1
 
-# CMD ["npm", "run", "preview", "--", "--port", "4173", "--host", "0.0.0.0", "--logLevel", "debug"]
+HEALTHCHECK --interval=30s --timeout=3s \
+  # CMD curl --fail https://localhost:4173/ --insecure || exit 1
+  CMD curl --fail http://localhost:4173/ || exit 1
+
 CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "4173"]
-# CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "4173", "--https", "--key", "./certs/dev.fantasy-helper.ru-key.pem", "--cert", "./certs/dev.fantasy-helper.ru.pem"]
